import React from 'react';
import { Grid, Row, Col } from 'react-flexbox-grid';
import gridStyles from 'styles/base/grid.scss';
import baseStyles from 'styles/base/base.scss';
import logo from 'assets/images/logo.png';

const TermsOfService = () => (
  <Grid fluid className={gridStyles.mainGrid}>
    <Row className={gridStyles.fullHeight}>
      <Row top="xs" className={gridStyles.fullWidth}>
        <Col xs={8} className={baseStyles.baseMarginTop}>
          <img alt="Logo" src={logo} />
        </Col>
      </Row>
      <Row bottom="xs" className={baseStyles.fullWidth}>
        <Col xs={12}>
          <h1>Terms of Use</h1>
          <p>Last updated: December 4, 2017</p>
          <p>PLEASE NOTE THAT YOUR USE OF AND ACCESS TO THE SERVICES (AS DEFINED BELOW) ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THESE TERMS, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.</p>
          <p>These Terms of Use (these &ldquo;Terms&rdquo;) represent an agreement between you and Liquid financial services, Inc. (&ldquo;Liquid&rdquo;) and contain the terms and conditions governing your use of and access to: (1) our website at <a href="https://helloliquid.com">helloliquid.com</a>&nbsp;and all of our other websites to which these Terms are posted (collectively, the &ldquo;Website&rdquo;); (2) our mobile applications to which these Terms are posted (collectively, the &ldquo;Application&rdquo;); and (3) any products, services, and applications made available through the Website or the Application (together with the Website and the Application, the &ldquo;Services&rdquo;). &ldquo;You&rdquo; and &ldquo;your&rdquo; mean the person who uses or accesses the Services. &ldquo;We,&rdquo; &ldquo;us,&rdquo; and &ldquo;our&rdquo; mean Liquid and its successors, affiliates, and assignees.</p>
          <p>Your use of and access to the Services are subject at all times to these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a> . Please read these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a> carefully. By using or accessing the Services or by clicking to agree to these Terms when that option is made available to you, you represent that you have read and understand these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a> and you agree to be bound by these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a> . If you do not agree to all the terms and conditions of these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a>, do not use or access the Services.</p>
          <h2>YOUR CONSENT TO USE ELECTRONIC SIGNATURES AND COMMUNICATIONS</h2>
          <p>Your Consent.&nbsp;To the extent permitted by applicable law, you consent to use electronic signatures and to electronically receive all records, notices, statements, communications, and other items for all services provided to you under these Terms and in connection with your relationship with us (collectively, &ldquo;Communications&rdquo;) that we may otherwise be required to send or provide you in paper form (e.g., by mail). By accepting and agreeing to these Terms electronically, you represent that: (1) you have read and understand this consent to use electronic signatures and to receive Communications electronically; (2) you satisfy the minimum hardware and software requirements specified below; and (3) your consent will remain in effect until you withdraw your consent as specified below.</p>
          <p>Your Right to Withdraw Your Consent.&nbsp;Your consent to receive Communications electronically will remain in effect until you withdraw it. You may withdraw your consent to receive further Communications electronically at any time by contacting us at <a href="mailto:help@helloliquid.com">help@helloliquid.com</a>. Any withdrawal of your consent to receive Communications electronically will be effective only after we have a reasonable period of time to process your withdrawal. Please note that withdrawal of your consent to receive Communications electronically will not apply to Communications electronically provided by us to you before the withdrawal of your consent becomes effective.</p>
          <p>You Must Keep Your Contact Information Current With Us.&nbsp;In order to ensure that we are able to provide Communications to you electronically, you must notify us of any change in your email address and your mobile device number or other text message address by updating your profile on the Website or the Application.</p>
          <p>Copies of Communications.&nbsp;You should print and save and/or electronically store a copy of all Communications that we send to you electronically.</p>
          <p>Hardware and Software Requirements.&nbsp;In order to access and retain Communications provided to you electronically, you must have: (1) a valid email address; (2) a computer or other mobile device (such as tablet or smart phone) that operates on a platform like Windows or iOS; (3) a connection to the Internet; (4) a Current Version of Internet Explorer 8 (or higher), Mozilla Firefox 7.0, Safari 5, or Chrome 15; (5) a Current Version of a program that accurately reads and displays PDF files, such as Adobe Acrobat Reader version 7 or higher; (6) a computer or device and an operating system capable of supporting all of the above; and (7) a printer to print out and save Communications in paper form or electronic storage to retain Communications in an electronic form. &ldquo;Current Version&rdquo; means a version of the software that is currently being supported by its publisher.</p>
          <p>Changes.&nbsp;We reserve the right, in our sole discretion, to communicate with you in paper form. In addition, we reserve the right, in our sole discretion, to discontinue the provision of electronic Communications or to terminate or change the terms and conditions on which we provide electronic Communications. Except as otherwise required by applicable law, we will notify you of any such termination or change by updating these Terms on the Website and the Application or delivering notice of such termination or change electronically.</p>
          <h2>Are there any fees for using the Services?</h2>
          <p>We may charge a monthly fee (the &ldquo;Monthly Fee&rdquo;) for our ongoing services that track funds in your Bank Account. The current amount of the Monthly Fee is disclosed on the Website and the Application. We may debit the Monthly Fee on a monthly basis from your Bank Account pursuant to your ACH authorization provided above. The Monthly Fee is non-refundable, except as otherwise required by applicable law. We may change the amount, frequency, and debit date of the Monthly Fee from time to time in our sole discretion. We will notify you in advance of any change to the Monthly Fee by sending you an email, by posting a notice on the Website and the Application, and/or by any other method permitted by applicable law. By accessing or using the Services after any change to the Monthly Fee takes effect, you agree to pay the Monthly Fee, as modified.</p>
          <h2>What are the requirements to use the Services?</h2>
          <p>In order to use the Services, you must: (a) accept and agree to these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a>; (b) register with us on the Website or the Application; (c) provide&nbsp;all information requested by us, such as your name, email address, mobile device number, online credentials for your Bank Account, and such other information as we may request from time to time (collectively, &ldquo;User Information&rdquo;); and (d) pay the Monthly Fee as specified herein. You represent and warrant that all User Information you provide us from time to time is truthful, accurate, current, and complete, and you agree not to misrepresent your identity or your User Information. You agree to promptly notify us of changes to your User Information by updating your Liquid account on the Website or the Application; provided, however, that you must notify us at least three Business Days before any changes to your Bank Account information, including, but not limited to, the closure of your Bank Account for any reason by emailing help@helloliquid.com or by updating your Liquid account via the Website or the Application. If we approve your registration, you will be authorized to use the Services, subject to these Terms.</p>
          <p>For our compliance purposes and in order to provide the Services to you, you hereby authorize us to, directly or through a third-party, obtain, verify, and record information and documentation that helps us verify your identity and Bank Account information. When you register for the Services and from time to time thereafter, we may require you to provide and/or confirm information and documentation that will allow us to identify you, such as:</p>
          <ul>
            <li>A copy of your government-issued photo ID, such as a passport or driver&rsquo;s license;</li>
            <li>A copy of a utility bill, bank statement, affidavit, or other bill, dated within three months of our request, with your name and U.S. street address on it; and</li>
            <li>Such other information and documentation that we may require from time to time.</li>
          </ul>
          <p>By using the Services and providing User Information to us, you automatically authorize us to obtain, directly or indirectly through our third-party service providers and without any time limit or the requirement to pay any fees, information about you and your Bank Account from the financial institution holding your Bank Account and other third-party websites and databases as necessary to provide the Services to you. For purposes of such authorization, you hereby grant Liquid and our third-party service providers a limited power of attorney, and you hereby appoint Liquid and our third-party service providers as your true and lawful attorney-in-fact and agent, with full power of substitution and resubstitution, for you and in your name, place, and stead, in any and all capacities, to access third-party websites, servers, and documents; retrieve information; and use your User Information, all as described above, with the full power and authority to do and perform each and every act and thing requisite and necessary to be done in connection with such activities, as fully to all intents and purposes as you might or could do in person. YOU ACKNOWLEDGE AND AGREE THAT WHEN LIQUID OR OUR THIRD-PARTY SERVICE PROVIDERS ACCESS AND RETRIEVE INFORMATION FROM SUCH THIRD-PARTY WEBSITES, LIQUID AND OUR THIRD-PARTY SERVICE PROVIDERS ARE ACTING AS YOUR AGENT, AND NOT THE AGENT OR ON BEHALF OF THE THIRD PARTY. You agree that other third parties shall be entitled to rely on the foregoing authorization, agency, and power of attorney granted by you. You understand and agree that the Services are not endorsed or sponsored by any third-party account providers accessible through the Services. We make no effort to review information obtained from the financial institution holding your Bank Account and other third-party websites and databases for any purpose, including, but not limited to, accuracy, legality, or non-infringement. As between Liquid and our third-party service providers, Liquid owns your confidential User Information.</p>
          <p>The information you provide us is subject to our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a>.</p>
          <h2>What do I do if my mobile device is lost or stolen or if I suspect someone has gained unauthorized access to my username or password?</h2>
          <p>If your mobile device is lost or stolen or if you suspect someone has gained unauthorized access to your username or password, you must contact us immediately at help@helloliquid.com. In order to take any action, you will need to provide certain User Information so we can verify your identity.</p>
          <h2>How does Liquid communicate with me about the Services?</h2>
          <p>In order to use the Services, you must provide and verify your mobile device number or other text message address to us, and you must expressly consent to receive text messages relating to the Services at that number or address. Third-party data and message fees may apply. To verify your mobile device number or text message address, we may send you a code via text message to the mobile device number or text message address you provide, and you must enter that code as instructed by us. If you change your mobile device number or text message address, you must promptly provide and verify your new mobile device number or text message address.</p>
          <p>In addition, if you provide your email address to us, we may send you important notices via email about the Services.</p>
          <h2>What do I need to know about third-party websites?</h2>
          <p>The Services may contain links or connections to third-party websites or services that are not owned or operated by us or our third-party service providers or licensors. We provide such links and connections for your reference only. We do not control such third-party websites or services and are not responsible for their availability or content. Our inclusion of such links and connections does not imply our endorsement of such third-party websites or services or any association with their owners or operators. We assume no liability whatsoever for any such third-party websites or services or any content, features, products, or practices of such third-party websites or services. Your access and use of such third-party websites and services is subject to applicable third- party terms and conditions and privacy policies. We encourage you to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize.</p>
          <h2>What if I want to stop using the Services?</h2>
          <p>You may stop using the Services and cancel these Terms at any time by contacting us at help@helloliquid.com and providing sufficient information for us to verify your identity.</p>
          <h2>What about my privacy?</h2>
          <p>Liquid takes the privacy of its users very seriously. You understand that by using the Services, you consent to the collection, use, storage, and disclosure of your information as set forth in these Terms and our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a>.</p>
          <h2>What else do I need to know about the Services?</h2>
          <p>Additional Terms. In conjunction with your access or use of the Services, you may be subject to additional terms, rules, policies, and conditions that are posted on the Website or the Application, including, but not limited to, terms and conditions for our referral or rewards programs (the &ldquo;Additional Terms&rdquo;), which are hereby incorporated by reference into these Terms. In the event of a conflict between any Additional Terms and these Terms, these Terms will control.</p>
          <p>Warranty Disclaimer. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW AND EXCEPT AS OTHERWISE EXPRESSLY PROVIDED IN THESE TERMS, YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES AND ALL INFORMATION, PRODUCTS, AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE SERVICES IS AT YOUR SOLE RISK. THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT ANY WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE AND OUR THIRD-PARTY SERVICE PROVIDERS EXPRESSLY DISCLAIM ANY AND ALL CONDITIONS, REPRESENTATIONS, AND WARRANTIES OF ANY KIND AS TO THE SERVICES AND ALL INFORMATION, PRODUCTS, AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE SERVICES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
          <p>WITHOUT LIMITING THE FOREGOING, WE AND OUR THIRD-PARTY SERVICE PROVIDERS MAKE NO WARRANTY THAT (A) THE SERVICES WILL MEET YOUR REQUIREMENTS, (B) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (C) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS, OR (E) ANY ERRORS IN THE SERVICES WILL BE CORRECTED. NO ORAL OR WRITTEN INFORMATION OR ADVICE OBTAINED BY YOU FROM US OR OUR THIRD-PARTY SERVICE PROVIDERS THROUGH OR FROM THE SERVICES WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.</p>
          <p>ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK, AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</p>
          <p>Limitation of Liability. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT LIQUID, ITS AFFILIATES, AND ITS AND THEIR RESPECTIVE EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, AND THIRD-PARTY SERVICE PROVIDERS WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR (A) THE PERFORMANCE OF THE SERVICES OR THE INABILITY TO USE THE SERVICES; (B) ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, WHETHER BASED IN CONTRACT, TORT, OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, EVEN IF SUCH PERSONS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHICH ARISE OUT OF OR ARE IN ANY WAY CONNECTED WITH THESE TERMS, THE SERVICES, OR CONTENT; (C) ANY EVENT BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
          <p>Indemnity.&nbsp;At our request, you agree to defend, indemnify, and hold harmless Liquid, its affiliates, and its and their respective employees, officers, directors, agents, and third- party service providers from and against any and all claims, suits, liabilities, damages (actual and consequential), losses, fines, penalties, costs, and expenses (including reasonable attorneys&rsquo; fees) arising from or in any way related to any third-party claims relating to your use of the Services, violation of these Terms, applicable law or any third-party rights, or your fraud or willful misconduct. Such indemnified parties reserve the right to assume the exclusive defense and control of any matter subject to indemnification by you, in which event you will cooperate in asserting any available defenses.</p>
          <p>Assignment.&nbsp;You may not transfer, assign, or delegate these Terms or your rights or obligations hereunder or your Liquid Account in any way (by operation of law or otherwise) without our prior written consent. To the extent permitted by applicable law, we may transfer, assign, or delegate these Terms and our rights and obligations hereunder without your consent.</p>
          <p>Third-Party Beneficiary. You agree that our third-party services providers are third- party beneficiaries of the applicable provisions of these Terms, with all rights to enforce such provisions as if such service providers were a party to these Terms.</p>
          <p>Governing Law. These Terms are made under and will be governed by and construed in accordance with the laws of the State of California, consistent with the Federal Arbitration Act, without giving effect to any principles that provide for the application of the law of another jurisdiction.</p>
          <p>DISPUTE RESOLUTION BY BINDING ARBITRATION: JURY TRIAL WAIVER: CLASS ACTION WAIVER. For any and all controversies, disputes, demands, claims, or causes of action between you and us (including the interpretation and scope of this Section and the arbitrability of the controversy, dispute, demand, claim, or cause of action) relating to the Services or these Terms (as well as any related or prior agreement that you may have had with us), you and we agree to resolve any such controversy, dispute, demand, claim, or cause of action exclusively through binding and confidential arbitration. The arbitration will take place in the federal judicial district of your residence. As used in this Section, &ldquo;we&rdquo; and &ldquo;us&rdquo; mean Liquid and its subsidiaries, affiliates, predecessors, successors, and assigns and all of its and their respective employees, officers, directors, agents, and representatives. In addition, &ldquo;we&rdquo; and &ldquo;us&rdquo; include any third party providing any product, service, or benefit in connection with the Services or these Terms (as well as any related or prior agreement that you may have had with us) if such third party is named as a co-party with us in any controversy, dispute, demand, claim, or cause of action subject to this Section.</p>
          <p>Arbitration will be subject to the Federal Arbitration Act and not any state arbitration law. The arbitration will be conducted before one commercial arbitrator from the American Arbitration Association (&ldquo;AAA&rdquo;) with substantial experience in resolving commercial contract disputes. As modified by these Terms, and unless otherwise agreed upon by the parties in writing, the arbitration will be governed by the AAA&rsquo;s Commercial Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer Related Disputes (collectively, the &ldquo;Rules and Procedures&rdquo;).</p>
          <p>You should review this provision carefully. To the extent permitted by applicable law, you are GIVING UP YOUR RIGHT TO GO TO COURT to assert or defend your rights EXCEPT for matters that you file in small claims court in the state or municipality of your residence within the jurisdictional limits of the small claims court and as long as such matter is only pending in that court. Additionally, notwithstanding this agreement to arbitrate, either party may seek emergency equitable relief in federal court if it has jurisdiction or, if it does not, in a state court located in the federal judicial district of your residence in order to maintain the status quo pending arbitration, and each party hereby agrees to submit to the exclusive personal jurisdiction of the courts located within the federal judicial district of your residence for such purpose. A request for interim measures will not be deemed a waiver of the obligation to arbitrate.</p>
          <p>Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury. You are entitled to a FAIR HEARING, BUT the arbitration procedures may be SIMPLER AND MORE LIMITED THAN RULES APPLICABLE IN COURT. Arbitrators&rsquo; decisions are as enforceable as any court order and are subject to VERY LIMITED REVIEW BY A COURT.</p>
          <p>You and we must abide by the following rules: (A) ANY CLAIMS BROUGHT BY YOU OR US MUST BE BROUGHT IN THE PARTY&rsquo;S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING; (B) THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON&rsquo;S CLAIMS, MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND MAY NOT AWARD CLASS-WIDE RELIEF; (c) in the event that you are able to demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, we will pay as much of your filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive as compared to the cost of litigation, (d) we also reserve the right, in our sole and exclusive discretion, to assume responsibility for any or all of the costs of the arbitration; (e) the arbitrator will honor claims of privilege and privacy recognized at law; (f) the arbitration will be confidential, and neither you nor we may disclose the existence, content, or results of any arbitration, except as may be required by applicable law or for purposes of enforcement of the arbitration award; (g) subject to the limitation of liability provisions of these Terms, the arbitrator may award any individual relief or individual remedies that are expressly permitted by applicable law; and (h) each party will pay its own attorneys&rsquo; fees and expenses, unless there is a statutory provision that requires the prevailing party to be paid its fees and litigation expenses and the arbitrator awards such attorneys&rsquo; fees and expenses to the prevailing party, and, in such instance, the fees and costs awarded will be determined by the applicable law.</p>
          <p>This Section will survive termination of your Liquid Account and these Terms as well as any voluntary payment of any debt in full by you or any bankruptcy by you or us. With the exception of subparts (a) and (b) of this Section (prohibiting arbitration on a class or collective basis), if any part of this arbitration provision is deemed to be invalid, unenforceable, or illegal, or otherwise conflicts with the Rules and Procedures, then the balance of this arbitration provision will remain in effect and will be construed in accordance with its terms as if the invalid, unenforceable, illegal, or conflicting part was not contained herein. If, however, either subpart (a) or (b) of this Section is found to be invalid, unenforceable, or illegal, then the entirety of this arbitration provision will be null and void, and neither you nor we will be entitled to arbitration. If for any reason a claim proceeds in court rather than in arbitration, the dispute will be exclusively brought in federal court if it has jurisdiction or, if it does not, in a state court located in the federal judicial district of your residence.</p>
          <p>If you wish to opt out of this arbitration provision, you must notify us of your election in writing within 30 days of the date that you first became subject to this arbitration provision or within 30 days of the effective date of any material change to these Terms by sending a written notice to us by certified mail at the following address: Liquid financial services, Inc., 235 Montgomery St., Suite 650, San Francisco, CA 94104, Attn: Arbitration Opt-Out. Your opt-out notice must include your name, address, phone number, and email address.</p>
          <p>For more information on the AAA, the Rules and Procedures, or the process for filing an arbitration claim, you may call the AAA at 800-778-7879 or visit the AAA website at <a href="http://www.adr.org">http://www.adr.org</a>.</p>
          <p>Miscellaneous. You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that we may, in our sole discretion, do any of the foregoing on your behalf or for ourselves. The failure of either you or us to exercise, in any way, any right herein will not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms will otherwise remain in full force and effect and enforceable. These Terms, together with our <a href="https://app.helloliquid.com/privacy_policy">Privacy Policy</a>, constitute the entire and sole agreement between you and us with respect to the Services and supersedes all prior understandings, arrangements, or agreements, whether written or oral, regarding the Services. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of Liquid, and you do not have any authority of any kind to bind Liquid in any respect whatsoever.</p>
          <h2>Will Liquid ever change these Terms or the Services?</h2>
          <p>We may add to or terminate any of the Services or amend these Terms at any time, in our sole discretion, without providing notice to you, subject to applicable law. We reserve the right, subject to applicable law, to deliver to you any notice of changes to existing terms or the addition of new terms by posting an updated version of these Terms on the Website and the Application or delivering notice thereof to you electronically. You are free to decide whether or not to accept a revised version of these Terms, but accepting these Terms, as revised, is required for you to continue accessing or using the Services. If you do not agree to these Terms or any revised version of these Terms, your sole recourse is to terminate your access or use of the Services. Except as otherwise expressly stated by us, your access and use of the Services are subject to, and constitute your acceptance of, the version of these Terms in effect at the time of your access or use.</p>
          <h2>How can I contact Liquid?</h2>
          <p>If you have any questions, comments, or concerns regarding these Terms or the Services, please contact us at help@helloliquid.com, or Liquid financial services, Inc., c/Jesus 16 Local 2, 08012, Barcelona, Spain</p>
        </Col>
      </Row>
    </Row>
  </Grid>
);

export default TermsOfService;
